# Generated by Django 2.2.1 on 2019-05-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('received', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=999)),
            ],
        ),
    ]
