# Generated by Django 2.2.1 on 2019-05-06 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('estate', '0001_initial'),
        ('user', '0005_auto_20190506_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=32)),
                ('offer_made', models.DateTimeField()),
                ('payed', models.BooleanField()),
                ('expires', models.DateTimeField()),
                ('counter_offer_to', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='offer.Offer')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Estate')),
                ('offer_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('payment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Payment')),
            ],
        ),
    ]
