# Generated by Django 2.2.1 on 2019-05-10 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20190506_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
