# Generated by Django 2.2.1 on 2019-05-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20190510_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='counter_offer_to',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='payment',
        ),
    ]
