# Generated by Django 2.2.1 on 2019-05-06 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_auto_20190506_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
                ('size', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('price', models.IntegerField()),
                ('fasteignamat', models.IntegerField()),
                ('brunabotamat', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('year_built', models.IntegerField()),
                ('entry', models.BooleanField()),
                ('garage', models.BooleanField()),
                ('description', models.CharField(max_length=999)),
                ('open_house', models.DateTimeField()),
                ('views', models.IntegerField()),
                ('elevator', models.BooleanField()),
                ('date_listed', models.DateTimeField()),
                ('estate_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
