# Generated by Django 2.2.1 on 2019-05-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=999)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Estate')),
            ],
        ),
    ]
