# Generated by Django 2.2.1 on 2019-05-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_auto_20190507_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
