# Generated by Django 2.2.1 on 2019-05-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_estate_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='static/images/estates'),
        ),
    ]
