# Generated by Django 2.2.1 on 2019-05-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0007_auto_20190509_1805'),
        ('estate', '0006_auto_20190510_0835'),
    ]

    operations = [
    ]
