# Generated by Django 2.2.1 on 2019-05-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0008_merge_20190510_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='images',
        ),
        migrations.CreateModel(
            name='HouseImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_logo', models.FileField(upload_to='')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Estate')),
            ],
        ),
    ]
