# Generated by Django 2.2.1 on 2019-05-10 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0011_auto_20190510_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatePictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='estate',
            name='images',
            field=models.FileField(default=1, max_length=9999, upload_to='media'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HouseImg',
        ),
        migrations.AddField(
            model_name='estatepictures',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Estate'),
        ),
    ]
