# Generated by Django 2.2.1 on 2019-05-06 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190505_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='estates',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='messages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='municipiality',
            field=models.CharField(blank=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='offers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.IntegerField(blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_roles',
            field=models.TextField(blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
