# Generated by Django 2.2.1 on 2019-05-10 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_auto_20190510_0835'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_auto_20190507_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.CharField(max_length=9999)),
                ('kennitala', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Municipality')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
