# Generated by Django 2.2.1 on 2019-05-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kennitala',
            field=models.BigIntegerField(),
        ),
    ]
