# Generated by Django 2.2.1 on 2019-05-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190512_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(max_length=9999, upload_to='media'),
        ),
    ]
