# Generated by Django 2.2.1 on 2019-05-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190512_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(max_length=9999, upload_to='media/users'),
        ),
    ]
